name: Validate

on:
  push:
    branches:
      - test-361
  workflow_dispatch:
    

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - run: cat requirements.txt
      - name: Install lsb-release
        run: |
          apt-get update
          apt-get install -y lsb-release
      - name: Create /etc/lsb-release
        run: |
          echo "DISTRIB_RELEASE=24.04" | tee -a /etc/lsb-release
      - uses: priya-kinthali/srcomp-validate-action@test-action-361
      - run: cat requirements.txt
